version: "3.9"
services:
    server:
      build:
        context: ./
        dockerfile: ./Dockerfile
      container_name: django
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./server:/server
      ports:
        - "8000:8000"
      depends_on:
        - db
        - redis
      environment: &server_env
        DEBUG: 'True'
        DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'
        SECRET_KEY: ${secret_KEY}
        TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
        TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
        TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}

    db:
      image: postgres:14.1-alpine
      container_name: postgres
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"

    redis:
      image: redis:6.2
      command: redis-server
      ports:
        - "6379:6379"

    celery:
      build:
        context: ./
        dockerfile: ./Dockerfile
      container_name: celery
      command: bash -c "cd /server && python -m celery -A config.celery worker --loglevel=info"
      volumes:
        - ./server:/server
      depends_on:
        - server
      environment: *server_env
