# Generated by Django 3.2.8 on 2021-10-24 14:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211024_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAds',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.ad',),
            managers=[
                ('archive', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='в архиве'),
        ),
    ]
