# Generated by Django 3.2.8 on 2021-10-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211027_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='itn',
            field=models.CharField(default='', max_length=10, verbose_name='идентификационный номер налогоплательщика'),
            preserve_default=False,
        ),
    ]
