# Generated by Django 3.2.9 on 2021-11-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_subscription_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(max_length=4, verbose_name='проверочный код, 4 цифры')),
                ('confirmed', models.BooleanField(default=False, verbose_name='номер подтверждён')),
                ('response', models.CharField(blank=True, max_length=1024, verbose_name='ответ от провайдера')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smslog', to='main.seller', verbose_name='продавец')),
            ],
            options={
                'verbose_name': 'Смс подтверждение',
                'verbose_name_plural': 'Смс подтверждения',
            },
        ),
    ]
