# Generated by Django 3.2.9 on 2021-11-24 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)], verbose_name='проверочный код, 4 цифры'),
        ),
    ]
