# Generated by Django 3.2.9 on 2021-11-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_smslog_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smslog',
            options={'verbose_name': 'смс подтверждение', 'verbose_name_plural': 'смс подтверждения'},
        ),
        migrations.RemoveField(
            model_name='smslog',
            name='response',
        ),
        migrations.AddField(
            model_name='smslog',
            name='celery_task',
            field=models.CharField(default='', editable=False, max_length=36, verbose_name='номер celery задачи'),
            preserve_default=False,
        ),
    ]
