# Generated by Django 3.2.9 on 2021-11-25 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_smslog_celery_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='celery_task',
        ),
        migrations.AddField(
            model_name='smslog',
            name='number_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='количество попыток ввода кода'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Не верный номер телефона.', regex='^\\+?1?\\d{11}$')], verbose_name='номер телефона (в формате +7)'),
        ),
    ]
