# Generated by Django 3.2.9 on 2021-12-04 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211125_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='number_attempts',
        ),
        migrations.AddField(
            model_name='smslog',
            name='sent_phone',
            field=models.CharField(blank=True, max_length=12, verbose_name='номер телефона, на который отправлен смс'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Неверный номер телефона.', regex='^\\+?1?\\d{11}$')], verbose_name='номер телефона (в формате +7)'),
        ),
    ]
