# Generated by Django 3.2.8 on 2021-10-30 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_seller_itn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
    ]
