# Generated by Django 3.2.9 on 2021-11-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211030_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='avatars', verbose_name='аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='itn',
            field=models.CharField(max_length=12, verbose_name='идентификационный номер налогоплательщика'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads_pictures', verbose_name='изображение объявления')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='main.ad', verbose_name='объявление')),
            ],
            options={
                'verbose_name': 'изображение объявления',
                'verbose_name_plural': 'изображения объявлений',
            },
        ),
    ]
