# Generated by Django 3.2.9 on 2021-11-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='заголовок подписки'),
            preserve_default=False,
        ),
    ]
